wandb_version: 1

project:
  desc: null
  value: Algorithm-Distillation-Training
group:
  desc: null
  value: Baselines
name:
  desc: null
  value: A2C-690604e8
checkpoints_path:
  desc: null
  value: ./checkpoints/darkroom/A2C-690604e8
environment_name:
  desc: null
  value: Dark-Room-v0
seed:
  desc: null
  value: 69
deterministic_torch:
  desc: null
  value: true
normalize_rewards:
  desc: null
  value: true
save_checkpoints:
  desc: null
  value: false
device:
  desc: null
  value: cuda
num_inputs:
  desc: null
  value: 1
num_actions:
  desc: null
  value: 5
num_episodes_for_actor:
  desc: null
  value: 30
gradient_clipping_norm:
  desc: null
  value: 5.0
num_actors:
  desc: null
  value: 10
discount:
  desc: null
  value: 0.99
mlp_layers_count:
  desc: null
  value: 3
hidden_dimension:
  desc: null
  value: 128
beta_1:
  desc: null
  value: 0.9
beta_2:
  desc: null
  value: 0.999
lr:
  desc: null
  value: 0.0001
epsilon:
  desc: null
  value: 0.0001
log_step:
  desc: null
  value: 20
episode_length:
  desc: null
  value: 20
single_stream:
  desc: null
  value: false
save_format:
  desc: null
  value: uint8
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.17.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1723673344
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 14
      - 16
      - 23
      - 24
      4: 3.10.12
      5: 0.17.6
      8:
      - 5
      10:
      - 3
      13: linux-x86_64
